name: Conda

on:
  workflow_dispatch:
  push:
    branches:
      - ci-actions
  pull_request:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, macos-latest] # windows-latest,
        python-version: ["3.6", "3.8"]

    runs-on: ${{ matrix.platform }}

    # The setup-miniconda action needs this to activate miniconda
    defaults:
      run:
        shell: "bash -l {0}"

    steps:
      - uses: actions/checkout@v2

      - name: Get conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: ${{ matrix.python-version }}
          channels: conda-forge
          
      - name: Prepare
        run: conda install conda-build conda-verify

      # - name: Build MOOS
      #   uses: ./.github/actions/build-moos-core
      - name: Checkout MOOS source
        uses: actions/checkout@v2
        with:
          repository: 'themoos/core-moos'
          path: '${{ github.workspace }}/core-moos'

      - name: 'Run CMake'
        uses: lukka/run-cmake@v3
        with:
          cmakeListsOrSettingsJson: CMakeListsTxtAdvanced
          cmakeListsTxtPath: '${{ github.workspace }}/core-moos/CMakeLists.txt'
          buildDirectory: '${{ github.workspace }}/core-moos/build'
          cmakeBuildType: 'Release'
          buildWithCMake: true
          cmakeAppendedArgs: '-DBUILD_SHARED_LIBS=OFF -DCMAKE_POSITION_INDEPENDENT_CODE=ON'

      - name: Install MOOS
        run: |
          cd ${{ github.workspace }}/core-moos/build
          cmake --install . --prefix ${{ github.workspace }}/.local
          echo "PATH=$PATH:${{ github.workspace }}/.local/bin" >> $GITHUB_ENV

      - name: Create setup.cfg
        run: |
          echo "[build_ext]" >> setup.cfg
          echo "include_dirs=${{ github.workspace }}/.local/include" >> setup.cfg
          echo "library_dirs=${{ github.workspace }}/.local/lib" >> setup.cfg
          cat setup.cfg

      - name: Build
        run: conda build conda.recipe

      - name: Install
        run: conda install -c ${CONDA_PREFIX}/conda-bld/ pymoos

      - name: Test
        run: python tests/test.py

      - name: Upload conda package
        uses: actions/upload-artifact@v2
        with:
          path: ${{ CONDA_PREFIX }}/conda-bld/*/*.bz2
