name: Pip

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - ci-actions

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-latest] # windows-latest,
        python-version: ["2.7", "3.5", "3.8", "3.9"]

    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Add requirements
      run: python -m pip install --upgrade wheel setuptools

    # Eventually Microsoft might have an action for setting up
    # MSVC, but for now, this action works:
    - name: Prepare compiler environment for Windows 🐍 2.7
      if: matrix.python-version == 2.7 && runner.os == 'Windows'
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64

    # This makes two environment variables available in the following step(s)
    - name: Set Windows 🐍 2.7 environment variables
      if: matrix.python-version == 2.7 && runner.os == 'Windows'
      shell: bash
      run: |
        echo "DISTUTILS_USE_SDK=1" >> $GITHUB_ENV
        echo "MSSdk=1" >> $GITHUB_ENV

    # Damn I wish this worked. When composite actions actually work move to .github/actions/build-moos-core
    # - name: Build MOOS
    #   uses: ./.github/actions/build-moos-core

    - name: Checkout MOOS source
      uses: actions/checkout@v2
      with:
        repository: 'themoos/core-moos'
        path: '${{ github.workspace }}/core-moos'

    - name: 'Run CMake'
      uses: lukka/run-cmake@v3
      with:
        cmakeListsOrSettingsJson: CMakeListsTxtAdvanced
        cmakeListsTxtPath: '${{ github.workspace }}/core-moos/CMakeLists.txt'
        buildDirectory: '${{ github.workspace }}/core-moos/build'
        cmakeBuildType: 'Release'
        buildWithCMake: true
        cmakeAppendedArgs: '-DBUILD_SHARED_LIBS=OFF -DCMAKE_POSITION_INDEPENDENT_CODE=ON'

    - name: Install MOOS
      run: |
        cd ${{ github.workspace }}/core-moos/build
        cmake --install . --prefix ${{ github.workspace }}
        echo "C_INCLUDE_PATH=${{ github.workspace }}/include" >> $GITHUB_ENV 
        echo "LIBRARY_PATH=${{ github.workspace }}/lib" >> $GITHUB_ENV
        echo "PATH=$PATH:${{ github.workspace }}/bin" >> $GITHUB_ENV

    # - name: Debug prints
    #   run: |
    #     echo "$(pwd)"
    #     find .

    - name: Create setup.cfg
      run: |
        echo "[build_ext]" >> setup.cfg
        echo "include_dirs=${{ github.workspace }}/include" >> setup.cfg
        echo "library_dirs=${{ github.workspace }}/lib" >> setup.cfg
        cat setup.cfg

    - name: Build and install
      run: pip install --verbose .

    - name: Test
      run: python tests/test.py
